import 'package:flutter/material.dart';

const Color appBlackColor = Colors.black;
const Color appColor = Color(0xff2978A2);
const Color appWhiteColor = Colors.white;
const Color appGrey1Color = Color(0xff7F7F85);
const Color appBlack1Color = Color(0xff272728);
const Color appGrey2Color = Color(0xffE3E4E9);
const Color appGreyColor = Color(0xffF1F2F6);
const Color appDarkGreyColor = Color(0xffE2E3E8);
const Color appLightGreyColor = Color(0xff7F7F85);
const Color appGreyColor5 = Color(0xff9D9DA3);
const Color appGrey3Color = Color(0xff6F7179);
const Color appGreyColor2 = Color(0xff323234);
const Color appGreyColor4 = Color(0xffD1D1D5);
const Color appDividerColor = Color(0xffE3E3E4);
const Color appBlueColor = Color(0xff2C97E9);
const Color appOrangeColor = Color(0xffFDAA0C);
const Color appDarkOrangeColor = Color(0xff50340D);
const Color appGreenColor = Color(0xff06D53F);
const Color appGreyArrowColor = Color(0xffB2B2B4);
const Color appRedColor = Colors.red;
